name: 'Setup pnpm Environment'
description: 'Setup Node.js and pnpm, install dependencies'
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      # Do not pin here; pnpm/action-setup will read the
      # exact version from package.json#packageManager (pnpm@10.0.0)

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "20"
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
