name: CI

on:
  workflow_dispatch:
  push:
    branches: 
      - 'feature-*'
      - 'feature/*'
      # 依存関係が更新されたときにも一応チェックする
      - 'dependabot/*' 
    paths: ['**/*.ts', '**/*.tsx', '**/*.js', '.github/**', '**/*.json']

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actions-security:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # 全てコミットハッシュ形式で指定する
      # @see https://zenn.dev/kou_pg_0131/articles/gha-static-checker
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      # GitHub Actions Lint - actionlint
      - name: Run actionlint
        uses: koki-develop/github-actions-lint/actionlint@62dfef5c9854a07712bad7af3bee7edb0c1109b1 # v1.4.1

      # GitHub Actions Lint - ghalint
      - name: Run ghalint
        uses: koki-develop/github-actions-lint/ghalint@62dfef5c9854a07712bad7af3bee7edb0c1109b1 # v1.4.1

  typescript-ci:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: '9'

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
          
      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck

      - name: Test
        run: pnpm test