name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release-please:
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - id: release-please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          release-type: node
          token: ${{ github.token }}
      - name: Wait for checks to complete
        if: ${{ steps.release-please.outputs.pr }}
        run: |
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.number')
          gh pr checks "$PR_NUMBER" --watch
        env:
          GH_TOKEN: ${{ github.token }}
          PR_JSON: ${{ steps.release-please.outputs.pr }}
      - name: Enable auto-merge for release PR
        if: ${{ steps.release-please.outputs.pr }}
        run: |
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.number')
          gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_JSON: ${{ steps.release-please.outputs.pr }}
