name: Weekly Article Summary Action

on:
  issue_comment:
    types:
      - created

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  claude-weekly-summary:
    if: contains(github.event.issue.labels.*.name, 'weekly-summary') && contains(github.event.issue.labels.*.name, 'claude-action') && contains(github.event.issue.body, '@claude')
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: '9'

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Extract date range from issue
        id: extract-dates
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const issueBody = context.payload.issue.body;
            
            // Extract START_DATE and END_DATE from issue body
            const startDateMatch = issueBody.match(/- 開始日: (\d{4}-\d{2}-\d{2})/);
            const endDateMatch = issueBody.match(/- 終了日: (\d{4}-\d{2}-\d{2})/);
            
            if (!startDateMatch || !endDateMatch) {
              throw new Error('日付情報がIssue本文から見つかりません');
            }
            
            const startDate = startDateMatch[1];
            const endDate = endDateMatch[1];
            
            core.setOutput('start_date', startDate);
            core.setOutput('end_date', endDate);
            
            console.log(`処理期間: ${startDate} - ${endDate}`);

      - name: Generate Weekly Summary with Claude
        uses: anthropics/claude-code-action@7c5a98d59d2464ae73f453c3e649f5b813374481 # v0.0.44
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          direct_prompt: ${{ github.event.issue.body }}
          max_turns: 5
          timeout_minutes: 15
        env:
          START_DATE: ${{ steps.extract-dates.outputs.start_date }}
          END_DATE: ${{ steps.extract-dates.outputs.end_date }}
          CLOUDFLARE_D1_TOKEN: ${{ secrets.CLOUDFLARE_D1_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_DATABASE_ID: ${{ secrets.CLOUDFLARE_DATABASE_ID }}